In [2]:

import pandas as pd
import numpy as np
from sklearn.linear_model import ElasticNet, LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.metrics import classification_report, mean_absolute_error, r2_score, f1_score, accuracy_score,log_loss
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis,QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.ensemble import VotingClassifier, VotingRegressor, BaggingClassifier, BaggingRegressor, \
    RandomForestClassifier, AdaBoostClassifier, AdaBoostRegressor,GradientBoostingClassifier,StackingClassifier
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from tqdm import tqdm
from xgboost import XGBClassifier

In [3]:
sonar=pd.read_csv('sonar.csv')
y=sonar["Class"]
X=sonar.drop("Class",axis=1)
le=LabelEncoder()
y=le.fit_transform(y)
score=[]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=25)
l_r=np.linspace(0.01,0.8,20)
n_est=[50,100,200]
max_d=[3,5,None]
for e in n_est:
    for n in l_r:
        gbm=XGBClassifier(learning_rate=n,n_estimators=e,random_state=25)
        gbm.fit(X_train,y_train)
        y_pred=gbm.predict_proba(X_test)
        score.append([e,n,log_loss(y_test,y_pred)])

df=pd.DataFrame(score,columns=["estimator","learning rate","log loss"])
df.sort_values("log loss")

    estimator  learning rate  log loss
26        100       0.259474  0.339126
46        200       0.259474  0.342016
48        200       0.342632  0.344885
8          50       0.342632  0.345894
45        200       0.217895  0.346994
28        100       0.342632  0.348081
47        200       0.301053  0.350749
25        100       0.217895  0.350928
6          50       0.259474  0.351308
27        100       0.301053  0.356144
7          50       0.301053  0.356760
5          50       0.217895  0.365207
29        100       0.384211  0.365326
49        200       0.384211  0.365338
42        200       0.093158  0.365662
43        200       0.134737  0.370371
44        200       0.176316  0.374200
9          50       0.384211  0.376626
41        200       0.051579  0.376978
22        100       0.093158  0.380031
24        100       0.176316  0.385353
23        100       0.134737  0.388818
4          50       0.176316  0.389107
58        200       0.758421  0.391186
38        100       0.758421  0.391186
18         50       0.758421  0.391187
30        100       0.425789  0.392380
50        200       0.425789  0.392380
2          50       0.093158  0.393322
21        100       0.051579  0.394562
13         50       0.550526  0.405286
3          50       0.134737  0.407179
10         50       0.425789  0.409599
33        100       0.550526  0.411196
53        200       0.550526  0.411196
35        100       0.633684  0.427517
55        200       0.633684  0.427517
15         50       0.633684  0.428047
52        200       0.508947  0.434432
32        100       0.508947  0.434432
11         50       0.467368  0.435129
1          50       0.051579  0.436878
12         50       0.508947  0.438178
59        200       0.800000  0.442436
39        100       0.800000  0.442436
19         50       0.800000  0.442436
31        100       0.467368  0.450772
51        200       0.467368  0.450772
14         50       0.592105  0.451244
54        200       0.592105  0.451424
34        100       0.592105  0.451424
40        200       0.010000  0.454145
17         50       0.716842  0.455569
37        100       0.716842  0.455577
57        200       0.716842  0.455578
20        100       0.010000  0.517469
16         50       0.675263  0.575345
36        100       0.675263  0.575354
56        200       0.675263  0.575354
0          50       0.010000  0.577003

In [4]:
from lightgbm import LGBMClassifier

rates=np.linspace(0.01,0.8,20)
n_est=[50,100,200]
depth=[3,5,None]
scores=[]
for r in tqdm(rates):
    for d in depth:
        for n in n_est:
            gbm=LGBMClassifier(max_depth=d,n_estmators=n,random_state=25,learning_rate=r,verbose=-1)
            gbm.fit(X_train,y_train)
            y_pred=gbm.predict_proba(X_test)
            score.append([d,n,log_loss(y_test,y_pred)])
df=pd.DataFrame(score,columns=["estimator","n_estimators","score"])
df.sort_values("score")

100%|██████████| 20/20 [00:06<00:00,  3.29it/s]

     estimator  n_estimators     score
78         3.0     50.000000  0.330297
80         3.0    200.000000  0.330297
79         3.0    100.000000  0.330297
26       100.0      0.259474  0.339126
76         NaN    100.000000  0.340906
..         ...           ...       ...
210        NaN     50.000000  0.850884
212        NaN    200.000000  0.850884
207        5.0     50.000000  0.850884
209        5.0    200.000000  0.850884
208        5.0    100.000000  0.850884

[240 rows x 3 columns]